### ISSUE TITLE
Additions to LFS (DEPS), PAKS

### ISSUE THREAD

**Issue by ummeegge** [siosios/Netdata-on-Ipfire#1]
Hello siosios,
first of all thanks for keeping this project up. Have build the 1.33.0 also and wanted to deliver some ideas.
Since you also use the netdata-installer.sh there are some configure options which might be interesting, have used
```bash
	cd $(DIR_APP) && echo -ne '\n' | \
		./netdata-installer.sh		\
			--disable-cloud		\
			--disable-telemetry	\
			--dont-start-it
```
but may there are more new switches which might be interesting.
The netdata-installer.sh uses also download functions while compilation for e.g. libuv and libuuid, since not every build environment does have an active DNS in chroot (except IPFire as build environment itself) you can enable it by setting up a DNS server in /etc/resolv.conf only for the build process. To build all packages on your own is still possible but may also a lot of work more.

Have used also the in- uninstaller and update scripts under */ipfire-2.x/src/paks whereby the user:group netdata, the run levels for the initscript but also some additional permissions can be set. The uninstall.sh can removes all this.

Some ideas, may there are interesting for you.

Best,

Erik

EDIT: Have pushed the new version --> https://gitlab.com/ummeegge/netdata-on-ipfire including package if you want to go for a checkout.

**Comment by siosios** [comment]
thank you Erik Ill check out the changes

update:
I see I missed a few crucial things in my efforts to do this and some mistakes.

**Comment by siosios** [comment]
I made modifications to include your changes. I stayed with /opt dir for the install, though it might be a bit confusing if someone installs or had installed a version of yours.

**Comment by ummeegge** [comment]
> I made modifications to include your changes. I stayed with /opt dir for the install, though it might be a bit confusing if someone installs or had installed a version of yours.

Hello siosios,
no problem at all, i pushed Netdata just to give you an overview and will delete it in a couple of days from Gitlab. May i take a look a little deeper to check if some other configure options makes sense but also may to go for some additional Python modules. The Nginx integration might be an idea too to setup some credentials and HTTPS since it is already prepared --> https://github.com/siosios/Netdata-on-Ipfire/blob/main/config/netdata/netdata.init#L19 to do so...

Again, great that you are working on this.

Best,

Erik
